spring:
  application:
    name: rodas-contabilidad
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/rodas-contabilidad
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    clean-on-validation-error: false
  management:
    security:
      enabled: true

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
    routes:
      enabled: true
